### ISSUE TITLE
images.csv contains decimal image ids, not hex as advertised. 

### ISSUE THREAD

**Issue by barryhunter** [openimages/dataset#1]
grep 5215831864_46f356962f_o ./images_2016_08/train/images.csv
**106528377697029**,https://c1.staticflickr.com/5/4129/5215831864_46f356962f_o.jpg,https://www.flickr.com/photos/brokentaco/5215831864,https://creativecommons.org/licenses/by/2.0/,https://www.flickr.com/people/brokentaco/,David,28 Nov 2010 Our new house.

Thats the demo image noted on https://github.com/openimages/dataset ...
**000060e3121c7305**,"https://c1.staticflickr.com/5/4129/5215831864_46f356962f_o.jpg",\
"https://www.flickr.com/photos/bro....

Converting 106528377697029 to hex, does yield 000060e3121c7305

( from https://storage.googleapis.com/openimages/2016_08/images_2016_08.tar.gz ) 

lables.csv contains the hex id
./machine_ann_2016_08/train/labels.csv:**000060e3121c7305**,0.9:/m/06ht1,0.9:/m/05wrt,0.8:/m/01l0mw,0.7:/m/03d2wd,0.7:/m/03nxtz,0.7:/m/023907r,0.7:/m/020g49,0.6:/m/0l7_8,0.6:/m/02rfdq,0.6:/m/038t8_,0.6:/m/03f6tq,0.6:/m/01s105,0.5:/m/01nblt

Not a major issue, but makes it slightly awkward to work with.

**Comment by gkrasin** [comment]
Acknowledged. Will fix soon.

**Comment by gkrasin** [comment]
And thank you for reporting it!

**Comment by gkrasin** [comment]
@barryhunter I have uploaded a new tarball with urls:
https://storage.googleapis.com/openimages/2016_08/images_2016_08_v2.tar.gz

Can you please download it and check that everything looks good to you?

**Comment by barryhunter** [comment]
thanks. that looks good :)

**Comment by gkrasin** [comment]
Great. Thanks again for telling about the issue: I would not have spotted it anytime soon without a hint.
