### ISSUE TITLE
OpenImages V6 data set

### ISSUE THREAD

**Issue by balesh-n** [openimages/dataset#100]
Dear All
Thanks for exposing OpenImages data Set
We could see 1M data is exposed out of 9 M
Any Plan to expose 8M in phasewise manner or so
If so, is it possible to share the plan.

Rds
Balesh

**Comment by jponttuset** [comment]
Hi Balesh,

Only a subset of ~1.9M images is directly downloadable from CVDF or Appen (see [downloads](https://storage.googleapis.com/openimages/web/download.html)). This corresponds to validation, test, and the subset of train where there are boxes annotated.

The rest of the images are only downloadable using the links to Flickr available in the "Image ID" files.

Best,
