### ISSUE TITLE
Decoding Openimages v6 mask coordinates

### ISSUE THREAD

**Issue by apoorvcn47** [openimages/dataset#105]
Hi,
New to ml. I am using V6 for semantic segmentation. in segmentations.csv, it has mask coordinates under the header clicks. These are set of three coordinates. first two coordinates being pixel values x and y with last coordinate being 0 or 1. Can anyone please explain to me what does this last coordinate stand for?

Thanks

**Comment by jponttuset** [comment]
Hi @apoorvcn47,
The masks themselves are in separate PNG files. These clicks are "corrective clicks" which means that are where the annotators clicked to correct the mask either to say that they are indeed foreground (1) or background (0). More details are in the [https://storage.googleapis.com/openimages/web/download.html](Download page) under "Format > Instance segmentation masks"
Best,

**Comment by apoorvcn47** [comment]
@jponttuset
Thank you so much
