### ISSUE TITLE
BadZipFile Error

### ISSUE THREAD

**Issue by BassieWitkin** [openimages/dataset#106]
I'm trying to download the dataset using fiftyone in python, and am getting the following error:
`BadZipFile: File is not a zip file`

When I tried manually downloading using the url that showed up in the error (https://storage.googleapis....), the folder downloaded but was unable to be unzipped.

The code worked on a different machine without an issue. 

Any ideas?

**Comment by jponttuset** [comment]
Can you share which was the problematic ZIP file?

**Comment by BassieWitkin** [comment]
The masks files from the test set- each time I ran the code, a different file gave the error. When I opened the folder I saw the file downloaded and even when I tried to unzip it manually, it didn't work- for some reason it was downloading empty or corrupted.

**Comment by jponttuset** [comment]
Hi @Bassie1,
I just downloaded all the mask files and none give me an error.
If you still have problems downloading the data, please reopen the bug and add more details (e.g. specific URL giving you problems).
Best,
