### ISSUE TITLE
I try to use postgesql save .but have extra data after last expected column

### ISSUE THREAD

**Issue by zsxgb** [openimages/dataset#12]
in psql 
I 'use \copy Images FROM '/home/zsx/桌面/OPENimages/images_2016_08/validation/images.csv' DELIMITER ',' CSV HEADER' commond save images.then psql gave me error.

extra data after last expected column
CONTEXT:  COPY images, line 2: "000026e7ee790996,validation,https://farm7.staticflickr.com/5769/21094803716_da3cea21b8_o.jpg,https:/..."

**Comment by gkrasin** [comment]
@zsxgb apologies, I forgot to update the doc after adding Thumbnail300KURL into images.csv:
https://github.com/openimages/dataset/wiki/Importing-into-PostgreSQL/_compare/c9b08ba7aa10a9208c8af26fe4101bfd95e33c2b...7fa802bf524e0c5ecd2251eb360d9e25937bb9f7

Can you please try [the updated instructions](https://github.com/openimages/dataset/wiki/Importing-into-PostgreSQL)?

**Comment by zsxgb** [comment]
Thank you for your help, these data have been imported.

**Comment by gkrasin** [comment]
I am glad it worked for you now. Let me know, if you hit any more issues, I will do my best to fix them.

**Comment by zsxgb** [comment]
In the end how many people have such a technical condition, such a large data set to deal with the number of CPU and distributed technology. I just inserted the data record into postgeresql. The database has been more than 10G. This is only a small part. I count all the picture data, about 2T or more. Of course. I am using this data set only for the purpose of learning to use postgresql. Prepare for my own dataset.
