### ISSUE TITLE
print  image vectors for new image (based on pretrained model)

### ISSUE THREAD

**Issue by koepermn** [openimages/dataset#22]
Thanks for providing the pretrained Inception v3 model.
At the moment the classfy.py function outputs the nearest class for a given Image, is it possible to provide a function that outputs the highdimensional vector of a (new) image ?  this could be useful to transform the image into a vector.

**Comment by krasin** [comment]
@koepermn have you looked into [tools/compute_bottlenecks.py](https://github.com/openimages/dataset/blob/master/tools/compute_bottleneck.py)? It outputs activations on the 'PreLogits' layer, which sounds exactly what you want.
