### ISSUE TITLE
Any comparison with imagenet inception v3 for transfer learning / visual search

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [openimages/dataset#26]
Hi I have integrated Open Images inception into Deep Video Analytics [1] for generating text tags for an image/frame. However currently I am using imagement pre trained inception v3 for visual search. Have you tried using Open Images inception for transfer learning / visual search is it better than the imagenet trained model? 
Thanks,

[1] https://deepvideoanalytics.com/

**Comment by adalisan** [comment]
Better is subjective, and one cannot do an apples-to-apples comparison since the openimages trained model is trained with another set of labels.   but the set of annotation labels is bigger, so you would have more coverage for visual search.
