### ISSUE TITLE
I want to delete openimages viewer

### ISSUE THREAD

**Issue by tzatter** [openimages/dataset#32]
Hello, gkrasin. How are you?

Sadly, Google banned my openimages viewer site as spam.
Along with this, my other sites related to the domain have also been banned from google search results.
To solve this problem, I need to delete my openimages site. 
May I delete openimages site?

**Comment by rkrasin** [comment]
Hi @tzatter 

As @gkrasin is not active anymore (I left Google, and the corp github account behind), answering from the current one.

Sorry to hear that the viewer (and your related websites) were marked as spam. This is clearly a false positive of the spam detection machine. Sadly, if if I was still with Google, I would have nearly zero options to fight that. So, yes, deleting the viewer seem to be the only safe option to me. :(

Thank you for the heads up.

**Comment by tzatter** [comment]
@rkrasin 
Thank you for your understanding.
I am going to delete the site when I confirm that rkrasin deleted the link written to the readme

**Comment by rkrasin** [comment]
Pull request created: https://github.com/openimages/dataset/pull/33

**Comment by tzatter** [comment]
@rkrasin 
Wow you always work fast!
Thank you!
I will keep the site a few days then delete it

**Comment by rkrasin** [comment]
@tzatter the pull request is merged; please, feel free to remove your wonderful viewer (sorry that I don't have any way to resolve the underlying reason to delete it)

**Comment by rkrasin** [comment]
And thank you for hosting it over the last 9 months.

**Comment by tzatter** [comment]
@rkrasin 
Thank you for your kindness.
I didn't use any php framework until this site was created by php framework known as laravel.
When I finished the laravel tutorials, I wanted to create something.
I was searching for deep learning and reading the google blog. then I found out this awesome openimages project.
Thank you for giving me the opportunity

**Comment by rkrasin** [comment]
A somewhat related update: Common Visual Data Foundation (CVDF) has published their own viewer for Open Images: http://www.cvdfoundation.org/datasets/open-images-dataset/vis

The viewer includes bounding boxes visualizer.

**Comment by nalldrin** [comment]
Closing issue since it seems resolved.
