### ISSUE TITLE
Pretrained model details

### ISSUE THREAD

**Issue by mayankbhagya** [openimages/dataset#37]
Where can I get some information about how the pretrained model was trained?
Which images were used for training? 
How well does the model perform? 
Which code was used for training?

**Comment by rkrasin** [comment]
@mayankbhagya I don't have a hand in the second release, but I was involved in the first one. My guess would be that all of this info will become available once the pretrained models are released. They are "coming soon", but last time it took 5 weeks for me to release the models. Let's hope it would be more smooth this time, but I would hold my breath.

**Comment by mayankbhagya** [comment]
Thanks @rkrasin 
The pretrained model which is currently available is based on v1. 
And I'm unable to find any training code or performance details corresponding to the v1 model. 
Is that info available?

**Comment by rkrasin** [comment]
@mayankbhagya the best description of the training procedure and performance can be found in [Learning From Noisy Large-Scale Datasets With Minim](https://arxiv.org/abs/1701.01619) by @andreasveit and others.

No training code was released; mostly, because TensorFlow was being actively massaged in the preparation to 1.0 and it was too hard to keep up with their renames. Sorry.

**Comment by mayankbhagya** [comment]
Many thanks @rkrasin!

**Comment by ddofer** [comment]
Hi, any update on a pretrained model? (Either for V1 or the new V2?). Thanks!

**Comment by rkrasin** [comment]
The V2 model has been released: https://github.com/openimages/dataset/pull/46
Notes on how it was trained: https://storage.googleapis.com/openimages/2017_07/oidv2-resnet_v1_101.readme.txt

```
-------------------------------
Details on model training:
-------------------------------
The model was trained using the tf-slim image classification model library
available at https://github.com/tensorflow/models/tree/master/research/slim. Vgg
input preprocessing was used with image resolution 299x299. The classification
layer is defined as
  logits, end_points = resnet_v1.resnet_v1_101(images, num_classes=5000)
  logits = tf.squeeze(logits, name='SpatialSqueeze')
  end_points['multi_predictions'] = tf.nn.sigmoid(
      logits, name='multi_predictions')

The model was trained asynchronously with 50 GPU workers and batch size 32 for
61995903 steps. RMSProp optimizer was used with the following settings:
  learning_rate = tf.train.exponential_decay(
      0.045,   # learning_rate
      slim.get_or_create_global_step(),
      552345,  # decay_steps
      0.94,    # learning_rate_decay_factor
      staircase=True
  )

  opt = tf.train.RMSPropOptimizer(
      learning_rate,
      0.9,  # decay
      0.9,  # momentum
      1.0   #rmsprop_epsilon
  )

The training data was formed by merging the machine-generated and human verified
annotations (filtered to the 5000 trainable classes):
- https://storage.googleapis.com/openimages/2017_07/annotations_machine_2017_07.tar.gz
- https://storage.googleapis.com/openimages/2017_07/annotations_human_2017_07.tar.gz
Human verified annotations were used whenever both were present.
```
