### ISSUE TITLE
[Feedback] Providing a method for integrity verification of dataset

### ISSUE THREAD

**Issue by louisgv** [openimages/dataset#38]
Hello, really appreciate this project. 

It would be really helpful if we can have an md5sum or better unique hash for each dataset so that the downloaded archive can be verified. Due to our network infrastructure, the download is often flaky, and thus even though we downloaded a 990MB archive, it turned out the archive was corrupted.

Thanks

**Comment by rkrasin** [comment]
Hi @louisgv,

images.csv has OriginalMD5 column. If you are downloading the images in the original resolution, it will help.

If you're downloading thumbnails, no checksum is possible, as (at least) Flickr generates these thumbnails on the fly. Every time these thumbnails are slightly different. More over, depends on the load, they might have more or less details in them.

**Comment by rkrasin** [comment]
Oh, I have misunderstood. You mean the hashes for archives with the metadata.

**Comment by rkrasin** [comment]
For the current set of archives:

```
$ sha1sum images_2017_07.tar.gz
e12e364e5aa44bd40dcdb78c54a7d8ed5c45f0ee  images_2017_07.tar.gz
$ sha1sum annotations_human_bbox_2017_07.tar.gz
31c7c72c5ac3c4c2f4becab0b4cfd5d5d5de7a3f  annotations_human_bbox_2017_07.tar.gz
$ sha1sum annotations_human_2017_07.tar.gz
5827193489d42635e5a78b467c4dede3ff066df3  annotations_human_2017_07.tar.gz
$ sha1sum annotations_machine_2017_07.tar.gz
511f006422c84984beb57578594e4b57c75a0b1b  annotations_machine_2017_07.tar.gz
$ sha1sum classes_2017_07.tar.gz
71ba8dd692ec3538543f45fdb2b88f6be59c096a  classes_2017_07.tar.gz
```

I expect that this will diverge from truth when minor updates are posted (but I hope that when it happens, the archive names will be different)

**Comment by rkrasin** [comment]
I was about to make a pull request for https://github.com/rkrasin/dataset/commit/1e3cede9b59290b3d1e32e23246c8f194ad34d35 but then realized that gzip already has a checksum (CRC32). It's relatively weak (just 4 bytes), but it's a good guard against bad internet connection.

How did you learn that the archive was corrupted?

**Comment by nalldrin** [comment]
Closing since this seems resolved (hash part of gzip).
