### ISSUE TITLE
importing the pretrained model

### ISSUE THREAD

**Issue by adalisan** [openimages/dataset#40]
I am trying to import the pretrained model checkpoint. 

new_saver = tf.train.import_meta_graph('/root/project_dir/docker_volume/model.ckpt.meta')
new_saver.restore(sess, tf.train.latest_checkpoint('./'))

I get op undefined error:
ValueError: No op named SSTableReader in defined operations.

I am using tensorflow 1.1.  Is there a specific tensorflow version I need to use?

**Comment by rkrasin** [comment]
Hi @adalisan,

the way it works is https://github.com/openimages/dataset/blob/master/tools/classify.py#L126
As for the SSTableReader op, the error only happens when you import the meta graph. Something that I forgot to test when worked on releasing that model. Quite possibly it's a solvable issue (as SSTableReader is more or less the same as TFRecords reader), but might require some .meta surgery.

**Comment by adalisan** [comment]
@rkrasin It is good to know the automatic ckpt loading functionality, but the main issue is the undefined op. Is that something you have defined in your copy of tensorflow , or is it available in tensorflow repo (perhaps in contrib?

**Comment by rkrasin** [comment]
@adalisan SSTableReader op is a Google-specific op. SSTable is the internal version of a data structure similar to TFRecords.

**Comment by adalisan** [comment]
@rkrasin So  .meta editing is something that can be done only by you? Would anybody at Google be able to do this soon?
Any other options? Like defining  SSTableREader as a wrapper for TFRecords?

Thanks

**Comment by rkrasin** [comment]
@adalisan no, I was speaking of theoretical options. I don't know exactly what needs to be done there.

Note that the model we speak about was trained on Open Images v1 annotations. The recently release v2 annotations are much cleaner, but I don't know if a new pre-trained model is coming (I am not with Google anymore, and don't have any inside knowledge about that)

**Comment by rkrasin** [comment]
As for defining a wrapper: I feel like it's even more work than the aforementioned surgery.

**Comment by rkrasin** [comment]
@adalisan a resnet101 model trained on OpenImages v2 just got released: https://github.com/openimages/dataset/pull/46

Would you like to train if it works for your problem (assuming it's still actual).

**Comment by nalldrin** [comment]
+1 To Ivan's recommendation of switching to the v2 model. (a) It should have superior performance, (b) I don't think you'll encounter this issue there. Please re-open this issue (or start a new one) if you still encounter trouble.

**Comment by adalisan** [comment]
I am carrying out other experiments right now, but might try the v2, when I get the chance. Do the graphs in these models have the label noise prediction in the CVPR paper by your group?
