### ISSUE TITLE
Any timeframe on releasing the new trained model?

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [openimages/dataset#49]
Hi, 
I saw that you plan on releasing a trained detector and recognition model on the updated dataset? 
Can you please tell me if you still plan on releasing the model and the approximate timeframe.

Thanks,
Akshay

**Comment by rkrasin** [comment]
@AKSHAYUBHAT An image-level classifier trained on OpenImages v2 was released a few days ago (see the updated [README.md](https://github.com/openimages/dataset/blob/master/README.md)). As for the object detector, I have no information I can share, sadly.

**Comment by domenicrosati** [comment]
@AKSHAYUBHAT @rkrasin Tensorflow released an object detection model on OpenImages V2 a couple days ago -> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by nalldrin** [comment]
Closing as we now have info in the README on how to get classifier and detector models.
