### ISSUE TITLE
Missing labels in dict.csv

### ISSUE THREAD

**Issue by yhenon** [openimages/dataset#5]
A number of labels appear in the annotation files but not in dict.csv.

For example:

	grep '/m/03s2xy' ./train/labels.csv | wc -l
	55
	grep '/m/03s2xy' ../dict.csv | wc -l        
	0

As far as I can tell this is the list for labels >50 occurences;

	/m/03s2xy
	/m/0dzlbx
	/m/025ryqs
	/m/0g4k1g
	/m/03s2yq
	/m/0c2r40
	/m/02rnlk1
	/m/0f8ym
	/m/0jncr
	/m/01x7t4
	/m/04mtl
	/m/05qwxx
	/m/0mf2
	/m/09bjv3

**Comment by gkrasin** [comment]
Acknowledge. @yhenon, thank you for the report, I will update dict.csv with the missing entries soon.

**Comment by gkrasin** [comment]
@yhenon I have updated dict.csv. The diff turned out a bit hairy, but in the end 37 missing labels were added. Please, take a look.

**Comment by gkrasin** [comment]
Verified that all reported mids were added in the fix:

```
$ for mid in $(cat ~/out/missing) ; \
do echo -n "Looking for ${mid}... " ; grep $mid dict.csv ; done
Looking for /m/03s2xy... "/m/03s2xy","polocrosse"
Looking for /m/0dzlbx... "/m/0dzlbx","iron man"
Looking for /m/025ryqs... "/m/025ryqs","comb"
Looking for /m/0g4k1g... "/m/0g4k1g","simca vedette"
Looking for /m/03s2yq... "/m/03s2yq","airco dh.2"
Looking for /m/0c2r40... "/m/0c2r40","packard 120"
Looking for /m/02rnlk1... "/m/02rnlk1","ford fairmont"
Looking for /m/0f8ym... "/m/0f8ym","amish"
Looking for /m/0jncr... "/m/0jncr","shinty"
Looking for /m/01x7t4... "/m/01x7t4","forester"
Looking for /m/04mtl... "/m/04mtl","lamborghini"
Looking for /m/05qwxx... "/m/05qwxx","ford model y"
Looking for /m/0mf2... "/m/0mf2","abbot"
Looking for /m/09bjv3... "/m/09bjv3","porsche 356/1"
```

Closing the issue. Please, reopen if you find another misssing label.
