### ISSUE TITLE
We made a object detection tutorial for open images

### ISSUE THREAD

**Issue by zeryx** [openimages/dataset#52]
My company and I recently published an in-depth tutorial on how to use the object detection annotations and image files with the [Tensorflow Object Detection]( https://github.com/tensorflow/models/tree/master/research/object_detection) API. We think it would be a great resource for newcomers to see when they take a look at the readme file. As we discovered for ourselves, Figuring out how to use this dataset with an existing object detection framework is non-trivial and could be quite daunting to the less experienced.
[Here's a link to the tutorial](https://blog.algorithmia.com/deep-dive-into-object-detection-with-open-images-using-tensorflow/)

**Comment by rkrasin** [comment]
@zeryx Thank you James for the tutorial. I played with an idea to make a similar pull request myself.

@vfgomes Victor, can you please take a look, when you're available for that?

**Comment by vfgomes** [comment]
Yes, will do. Thank you James for the tutorial. Expect an update by the end
of the week.

**Comment by vfgomes** [comment]
We are now pointing to it! Thanks again!

**Comment by RafaRuiz** [comment]
Hi @zeryx. For those that don't have 7TBs as memory, isn't it worth to resize (pre-proccess) the image whenever it gets downloaded and not after that?

**Comment by DeveloperRachit** [comment]
Dear team,

how much time GPU will take to train that dataset when will have GPU with 8 gb Ram Quadro M5000.
