### ISSUE TITLE
Open images viewer

### ISSUE THREAD

**Issue by tzatter** [openimages/dataset#6]
Is there the Open images viewer? such as [youtube8M dataset brower](https://research.google.com/youtube8m/explore.html)

I created the viewer

http://openimages.oldjpg.com/

this server response time is slow

sorry for not issue

**Comment by gkrasin** [comment]
@tzatter there's no official OpenImages viewer, unfortunately, at least, at the moment.

>http://openimages.oldjpg.com/
That looks awesome! Can I link to this viewer from README.md?

**Comment by tzatter** [comment]
thank you! please add this link untill official site is opened

**Comment by gkrasin** [comment]
Done. Thank you very much for your work!

**Comment by tzatter** [comment]
I'm glad. thank you, too :)
