### ISSUE TITLE
Why train-annotations-machine-imagelabels.csv missing the labeled bounding boxes?

### ISSUE THREAD

**Issue by YUFENGZHANG** [openimages/dataset#77]
Hello Thanks for releasing this treasure trove of images.
I am wondering why there is not labeled bounding boxes in train-annotations-machine-imagelabels.csv.

**Comment by jponttuset** [comment]
Not all images with image-level labels are annotated with boxes, "only" a subset of 1.7M images. You should therefore download the file containing the bounding boxes from the appropriate section of the open images download site (train-annotations-bbox.csv)

Best,

**Comment by YUFENGZHANG** [comment]
OK,Thank you for you reply!
