### ISSUE TITLE
some classes have the same description in the class-description.csv

### ISSUE THREAD

**Issue by yoosan** [openimages/dataset#79]
Hi:
 I found that some classes have the same description in the class-description.csv file. eg. 
  /m/01b7b, Bishop
  ....
  /m/027k49j, Bishop
  ...
  I also check some images in the validation set, the image with class /m/01b7b always has /m/027k49j labelled. Does it means /m/01b7b and /m/027k49j are the same category?
 Thanks, waiting for you reply.

**Comment by jponttuset** [comment]
Hi Yoosan,

The labels with same description but different ID are not the same label, they have subtle differences.
It happens in e.g. same car model but different versions of it.

Admittedly, `class-description.csv` does not contain this information, we are working on a way to release it.

Best,
