### ISSUE TITLE
What is the relationship between imagename and imageID?

### ISSUE THREAD

**Issue by Angel0003** [openimages/dataset#80]
hi，thanks very much for this dataset,I want to select out the image  and the corresponding box i need, but the  image in train-annotations-bbox.csv  is represented by imageID. The image in the training set  is represented by imagename. What is the relationship between imagename and imageID?how can i select out the image and the corresponding box i need？

**Comment by jponttuset** [comment]
Hi Angel0003

The imageID values in train-annotations-bbox.csv correspond to the filename of the images.

Best,

**Comment by shaburanigud** [comment]
I'm sorry but I'm kind of new to this as well.
Exactly how should I use the Image ID values to call the files?
