### ISSUE TITLE
Why did you move your site from GitHub?

### ISSUE THREAD

**Issue by markcmiller86** [openimages/dataset#82]
So, I am thinking of hosting a site with tens of thousands of small (300x300 or 600x600) rgb images as a gh-pages site. I went looking around to see if anyone had tried and had problems doing so on GitHub and found your site. It looks like you were once on GitHub, maybe as a gh-pages site? If so, any issues you ran into that cause you to move?

**Comment by krasin** [comment]
@markcmiller86 hi Mark,

answering as someone who set up the initial repository.

We did not use GitHub pages and the reason to use GitHub was to make something reasonable quick. 

For the first few releases the team kept the simple solution and then moved to a proper website, https://storage.googleapis.com/openimages/web/index.html.

**Comment by markcmiller86** [comment]
ok, thanks for info
