### ISSUE TITLE
How to call upon Image with Image ID?

### ISSUE THREAD

**Issue by shaburanigud** [openimages/dataset#83]
I'm sorry but I'm kind of new to this but I'm trying to use this to train my own object recognition model.
But the problem is, I can't find a way to call the according images with the image IDs and image filenames I got since I cannot understand how they are connected

May I ask exactly how should I use the Image ID values to call the image files?
I would very much appreciate it if it was in specific steps or even a simple example.

**Comment by svendaehne** [comment]
+1

**Comment by jponttuset** [comment]
That is correct.
ImageID is a string (e.g. 10eda1712b4b6f97), then the corresponding image is e.g. 10eda1712b4b6f97.jpg as found in the ZIP files downloaded from [CVDF or Figure Eight](https://storage.googleapis.com/openimages/web/download.html).

If you want to find the image in Flickr, then you have this information in the files in the 'Image IDs' row in the [Download](https://storage.googleapis.com/openimages/web/download.html) section.
