### ISSUE TITLE
Rotation related webpage returns access denied

### ISSUE THREAD

**Issue by derekhh** [openimages/dataset#84]
![image](https://user-images.githubusercontent.com/1497445/54569663-ece81480-4998-11e9-8cbe-dee4acfb70b3.png)

https://storage.googleapis.com/openimages/web/2018-05-10-rotation-information.html

This now returns access denied.

Anonymous caller does not have storage.objects.get access to openimages/web/2018-05-10-rotation-information.html.

**Comment by jponttuset** [comment]
Hi @derekhh 
The link was broken, the correct link is:
https://storage.googleapis.com/openimages/web/2018-05-17-rotation-information.html
Thanks for reporting this!
