### ISSUE TITLE
image aspect ratios

### ISSUE THREAD

**Issue by eyaler** [openimages/dataset#86]
I am interested in the aspect ratio of the images. as i could not find the image resolutions in the metadata, i was wondering if this is something you could publish.

**Comment by jponttuset** [comment]
We don't have this metadata available, sorry. But the images are, so you could easily compute the aspect ratios. Please be aware of the ['Rotation'](https://storage.googleapis.com/openimages/web/2018-05-17-rotation-information.html) field though. (More info on the [web](https://storage.googleapis.com/openimages/web/factsfigures.html))

**Comment by eyaler** [comment]
sure. i wanted to avoid downloading the images.
