### ISSUE TITLE
clarification on the relation between dataset versions

### ISSUE THREAD

**Issue by eyaler** [openimages/dataset#87]
i understand that v2 is a superset of v1. could you clarify the relations as regard to v3 and v4? specifically i am using v4/v5 and am interested to know whether i would get more bounding boxes if i add in images and data from v3 or v2.

**Comment by jponttuset** [comment]
- In terms of images, all versions work with the same set of 9M images.
- In terms of boxes, V5 is the most complete and accurate (a superset of them all)
- In V5 you also have segmentation :)
