### ISSUE TITLE
How to report invalid/questionable images?

### ISSUE THREAD

**Issue by monocongo** [openimages/dataset#94]
In the course of my work with images downloaded from OpenImages, I have come across a number of problematic images/bounding box annotations that I think should be removed or rectified. Is there a mechanism in place for this sort of QA?

A few examples of images from the "Person" class with wonky bounding boxes are attached below for illustration.
![invalid_image_6aba33edb9fe95cb](https://user-images.githubusercontent.com/1328158/70172762-664aa300-169f-11ea-866e-b5a4c099e93d.png)
![invalid_image_bcfc243a325a2ca9](https://user-images.githubusercontent.com/1328158/70172763-664aa300-169f-11ea-90eb-ba1143a4eb02.png)
![invalid_image_5dc899d00131b7d4](https://user-images.githubusercontent.com/1328158/70172764-664aa300-169f-11ea-97eb-e0736d521529.png)
![invalid_image_f9c48ae8a9e84897](https://user-images.githubusercontent.com/1328158/70180510-2dfe9100-16ae-11ea-90f3-8d481b46ea71.png)
![invalid_image_77f632ec95bf07da](https://user-images.githubusercontent.com/1328158/70181203-79656f00-16af-11ea-8e5b-23bb86144821.png)
![invalid_image_5bc24fd1de23195c](https://user-images.githubusercontent.com/1328158/70182069-21c80300-16b1-11ea-9238-c8f0f56fe383.png)
![invalid_image_74bcf3d8c63eae74](https://user-images.githubusercontent.com/1328158/70182200-5f2c9080-16b1-11ea-804c-04133daa6ce2.png)
![invalid_image_1d3cfb4202e92607](https://user-images.githubusercontent.com/1328158/70182670-4bcdf500-16b2-11ea-82cd-023a322638e5.png)
![invalid_image_d7c08ba3bb124f50](https://user-images.githubusercontent.com/1328158/70182969-e4fd0b80-16b2-11ea-97ab-4e7dec7eab5d.png)
![invalid_image_2c3f33943376fff3](https://user-images.githubusercontent.com/1328158/70183333-9603a600-16b3-11ea-9d84-bac907e3c7d7.png)

**Comment by monocongo** [comment]
Here's a "Car":

![invalid_image_48caab780670bb94](https://user-images.githubusercontent.com/1328158/70177964-5afc7500-16a9-11ea-95df-f9df7fd5637b.png)

**Comment by jponttuset** [comment]
Dear @monocongo,
We do not have any feedback loop for this sort of feedback.
However, some of these are correct according to our definition:
- The car pictures taken from the inside most probably have the "IsInside" attribute marked.
- People that are not completely visible most probably have the "IsTruncated" or "IsOccluded" attributes marked.
- People in the stadium probably have the "IsGroup" attribute marked.
See https://storage.googleapis.com/openimages/web/download.html#attributes for the description of the attributes.

**Comment by monocongo** [comment]
Thanks for your response, @jponttuset.

Before including images from OpenImages in my dataset I first [filter out all images with these attributes marked as true](https://github.com/monocongo/cvdata/blob/master/cvdata/openimages.py#L397) so none of the above images should be marked as such:

```
    # filter out images that are occluded, truncated, group, depiction, inside, etc.
    for reject_field in ("IsOccluded", "IsTruncated", "IsGroupOf", "IsDepiction", "IsInside"):
        df_images = df_images[df_images[reject_field] == 0]
```

I realize that this dataset is free and you get what you pay for, and my thoughts were to help with the quality control as a small contriibution to the project. I don't get the impression from your response that this is of much interest, nor is there a mecahnism in place to facilitate improvements when issues are detected. If this changes or if I'm mistaken then please contact me if I can help. I have [lists of images from the dataset that are problematic](https://github.com/monocongo/cvdata/tree/master/exclusions) that I use in my own work as an exclusion filter, in case that would be useful to others. I have not been able to go through more than a couple thousand images so far but I have found roughly 10% of the images to be problematic, so it appears that the dataset could benefit from additional attention to quality control.

**Comment by jponttuset** [comment]
Hi @monocongo,

> I don't get the impression from your response that this is of much interest, nor is there a mecahnism in place to facilitate improvements when issues are detected.
At the scale of Open Images, there is no easy way of incorporating this type of feedback, as we would need to verify any of the flagged content, with probably diminishing returns. I understand where you're coming from but I encourage you to think at the scale of 15 million boxes.

In any case, thank you for your feedback and for sharing the list of problematic images and I hope that Open Images is useful for your work despite its imperfections.

**Comment by monocongo** [comment]
I'm by no means an expert, but I wonder how useful a dataset is for training models for object detection if it's as dubious as Open Images appears to be? My assumption is that this sort of quality consideration should matter more than it appears to, as there seems to be an unexpectedly/surprisingly high percentage of low-quality images/boxes in this dataset. It may be that the adage "garbage in / garbage out" counterintuitively doesn't apply so much to the areas of endeavor where this dataset might typically be used? My assumption has been that removing questionable images such as the ones shown above will result in better training outcomes when using the dataset as training input for object detection models. Perhaps I should have run some experiments to verify this assumption before pestering you guys about it.

In any event, thanks for the work you guys do to provide this dataset to the community -- while not perfect it's nevertheless quite useful. Very appreciated!
