### ISSUE TITLE
Where can I download the OpenImage V2 dataset?

### ISSUE THREAD

**Issue by username123062** [openimages/dataset#97]
Dear all, 

Thanks for your attention! I am very interested in OpenImage V2 dataset. But, it's difficult to download it one image by one image according the the image link.

Thus, I want to ask that "is there a simple way to download the OpenImage V2 dataset?"
Or, does the OpenImage V4/V5/V6 include the OpenImage V2 ?

Thanks a lot.
@jponttuset @gkrasin @andreasveit @vfgomes

**Comment by jponttuset** [comment]
Hi!

The set of images does not change from version to version, so you can download the images as explained in the Open Images V6 website:
https://g.co/dataset/open-images

Best,
