### ISSUE TITLE
Request to add pretrained large-scale object detector to "Community Contributions"

### ISSUE THREAD

**Issue by xternalz** [openimages/dataset#99]
Hi, I had a paper published at ICCV'19 ("Scaling Object Detection by Transferring Classification Weights") on training very large-scale (5K categories) object detector using both Open Images box-levels and image-level annotations. A pretrained model (as well as training code) is shared in this repo https://github.com/xternalz/AE-WTN. I would like to request for it to be added to the "Extras" page for Open Images dataset under the "Community Contributions" section. Thanks.

**Comment by jponttuset** [comment]
Dear @xternalz,

Sorry for the super late reply. 
Thanks for getting in touch, I'll add it ASAP.

Best

**Comment by jponttuset** [comment]
Hi @xternalz, 
The change is now live (sorry for the delay... CVPR deadline...)
Best,
